version: "3"

services:
  app:
    build: .
    ports:
      - "3001:3000"
    volumes:
     - .:/usr/app
     - /usr/app/node_modules
    container_name: events-booking-frontend
    command: npm start
