version: "3"

services:
  server:
    build: .
    restart: always
    ports:
      - "3000:3000"
    links:
     - db
    volumes:
     - .:/usr/app
     - /usr/app/node_modules
    container_name: events-booking-backend
    command: npm start

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: events-booking-database
    logging:
      driver: "none"
